import Layout from './components/layout/layout'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <Layout>
        {children}
      </Layout>
      
    </html>
  )
}
